version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: ../docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    command: >
      sh -c "
        composer install &&
        cp .env.example .env &&
        php artisan key:generate &&
        php artisan migrate &&
        php artisan config:cache &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  node:
    image: node:20
    container_name: node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "sleep infinity"

volumes:
  mysql_data:
